include ~/.cache/wal/colors-kitty.conf

font_family	 CaskaydiaMono Nerd Font Mono
bold_font	 auto
italic_font	 auto
bold_italic_font auto

font_size 10.0
window_padding_width 25

background_opacity 0.8

cursor_trail                6
cursor_shape                block
shell_integration           no-cursor

shell_integration           enabled
strip_trailing_spaces       smart
notify_on_cmd_finish        unfocused
allow_remote_control        yes

map ctrl+t                  new_tab
map ctrl+w                  close_tab
map ctrl+shift+r            set_tab_title
map ctrl+]                  next_tab
map ctrl+[                  previous_tab
map ctrl+shift+h            move_tab_forward
map ctrl+shift+l            move_tab_backward

